#!/usr/bin/env python3
"""Convert one or more GPX files into a compact Monkey C track dataset.

The output uses integer coordinates in degrees * 1e5. This is deliberately
simple for the first watch feasibility prototype: no server, no Strava API,
and no runtime JSON parser on the watch.
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from typing import Iterable, Sequence

EARTH_RADIUS_M = 6_371_000.0


@dataclass(frozen=True)
class Point:
    lat: float
    lon: float


def parse_gpx(path: pathlib.Path) -> list[list[Point]]:
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError) as exc:
        raise ValueError(f"cannot parse {path}: {exc}") from exc

    tracks: list[list[Point]] = []
    for segment in root.findall(".//{*}trkseg"):
        points: list[Point] = []
        for node in segment.findall("{*}trkpt"):
            try:
                points.append(Point(float(node.attrib["lat"]), float(node.attrib["lon"])))
            except (KeyError, ValueError) as exc:
                raise ValueError(f"invalid track point in {path}") from exc
        if len(points) >= 2:
            tracks.append(points)
    return tracks


def to_local_meters(points: Sequence[Point]) -> list[tuple[float, float]]:
    if not points:
        return []
    origin = points[0]
    lat0 = math.radians(origin.lat)
    lon0 = math.radians(origin.lon)
    cos_lat = math.cos(lat0)
    return [
        (
            (math.radians(point.lon) - lon0) * cos_lat * EARTH_RADIUS_M,
            (math.radians(point.lat) - lat0) * EARTH_RADIUS_M,
        )
        for point in points
    ]


def perpendicular_distance(point: tuple[float, float], start: tuple[float, float], end: tuple[float, float]) -> float:
    if start == end:
        return math.dist(point, start)
    dx = end[0] - start[0]
    dy = end[1] - start[1]
    numerator = abs(dy * point[0] - dx * point[1] + end[0] * start[1] - end[1] * start[0])
    return numerator / math.hypot(dx, dy)


def simplify(points: Sequence[Point], tolerance_m: float) -> list[Point]:
    if len(points) <= 2 or tolerance_m <= 0:
        return list(points)

    planar = to_local_meters(points)

    def recurse(first: int, last: int, keep: set[int]) -> None:
        max_distance = 0.0
        max_index = -1
        for index in range(first + 1, last):
            distance = perpendicular_distance(planar[index], planar[first], planar[last])
            if distance > max_distance:
                max_distance = distance
                max_index = index
        if max_index >= 0 and max_distance > tolerance_m:
            keep.add(max_index)
            recurse(first, max_index, keep)
            recurse(max_index, last, keep)

    keep = {0, len(points) - 1}
    recurse(0, len(points) - 1, keep)
    return [points[index] for index in sorted(keep)]


def quantize(points: Iterable[Point]) -> list[tuple[int, int]]:
    return [(round(point.lat * 100_000), round(point.lon * 100_000)) for point in points]


def render_monkey_c(tracks: Sequence[Sequence[tuple[int, int]]]) -> str:
    lines = [
        "// Generated by tools/gpx_to_monkeyc.py. Do not edit manually.",
        "class HeatmapData {",
        "    static function tracks() {",
        "        return [",
    ]
    for track in tracks:
        lines.append("            [")
        for index, (lat, lon) in enumerate(track):
            suffix = "," if index < len(track) - 1 else ""
            lines.append(f"                [{lat}, {lon}]{suffix}")
        lines.append("            ],")
    if tracks:
        lines[-1] = lines[-1].rstrip(",")
    lines.extend(["        ];", "    }", "}", ""])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("gpx", nargs="+", type=pathlib.Path, help="GPX files exported from Strava or another source")
    parser.add_argument("-o", "--output", type=pathlib.Path, default=pathlib.Path("source/HeatmapData.mc"))
    parser.add_argument("--tolerance-m", type=float, default=8.0, help="Douglas-Peucker simplification tolerance")
    parser.add_argument("--max-points", type=int, default=3000, help="fail if generated total exceeds this watch-prototype guardrail")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    raw_tracks: list[list[Point]] = []
    for path in args.gpx:
        raw_tracks.extend(parse_gpx(path))

    tracks = [quantize(simplify(track, args.tolerance_m)) for track in raw_tracks]
    tracks = [track for track in tracks if len(track) >= 2]
    total_points = sum(len(track) for track in tracks)
    if total_points > args.max_points:
        print(
            f"error: {total_points} points exceeds --max-points={args.max_points}; "
            "increase simplification or use fewer activities",
            file=sys.stderr,
        )
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_monkey_c(tracks), encoding="utf-8")
    print(f"wrote {len(tracks)} track segments / {total_points} points to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
